# Generated by Django 5.2.1 on 2026-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubi_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='scramble',
            field=models.TextField(),
        ),
    ]
