# Generated by Django 5.2.1 on 2026-04-16 19:29

import cubi_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubi_web', '0002_alter_solve_scramble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='association_code',
            field=models.CharField(default=cubi_web.models.generate_association_code, max_length=32, unique=True),
        ),
    ]
